import argparse
import csv
import os
import re
from io import StringIO
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text


ANONYMOUS_USER_ID = -1
COPY_CHUNK_ROWS = 100_000
HELPER_ROOT = Path("dashboards/powerbi_data")
FK_CONSTRAINT_PATTERN = re.compile(
    r",\s*\n\s*CONSTRAINT\s+(?P<name>\w+)\s*\n"
    r"\s*FOREIGN\s+KEY\s*\((?P<columns>[^)]+)\)\s*\n"
    r"\s*REFERENCES\s+(?P<ref_table>\w+)\s*\((?P<ref_columns>[^)]+)\)",
    flags=re.IGNORECASE,
)

TABLE_LOAD_ORDER = [
    "dim_date",
    "dim_product",
    "dim_user",
    "dim_session",
    "dim_query",
    "fact_item_views",
    "fact_purchases",
    "fact_clicks",
    "fact_kpi_summary",
    "dim_model",
    "dim_item",
    "fact_metrics",
    "fact_recommendation_eval",
    "fact_marketing_kpis",
    "session_summary",
    "model_metrics_summary",
    "data_quality_summary",
]


def _postgres_url() -> str | None:
    load_dotenv()
    postgres_url = os.getenv("POSTGRES_URL")
    if not postgres_url:
        print("Error: POSTGRES_URL not found in .env")
        return None
    if postgres_url.startswith("postgres://"):
        postgres_url = postgres_url.replace("postgres://", "postgresql://", 1)
    return postgres_url


def _load_parquet(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return pd.read_parquet(path)


def _read_csv(path: Path, **kwargs) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return pd.read_csv(path, sep=";", **kwargs)


def _read_optional_csv(path: Path, sep: str = ",") -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path, sep=sep)


def _as_int(series: pd.Series, fill_value: int | None = None) -> pd.Series:
    out = pd.to_numeric(series, errors="coerce")
    if fill_value is not None:
        out = out.fillna(fill_value)
    return out.astype("Int64")


def _as_date(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, errors="coerce").dt.date


def _price_bucket(price_proxy: pd.Series) -> pd.Series:
    price = pd.to_numeric(price_proxy, errors="coerce")
    known = price.notna() & price.gt(0)
    buckets = pd.Series("Unknown", index=price.index, dtype="object")
    if known.any():
        ranked = pd.qcut(
            price[known].rank(method="first"),
            q=4,
            labels=["Low", "Mid", "High", "Premium"],
        )
        buckets.loc[known] = ranked.astype("object")
    return buckets


def _split_sql_batches(schema_sql: str) -> list[str]:
    batches: list[str] = []
    current: list[str] = []

    def add_statement(statement: str) -> None:
        for part in statement.split(";"):
            part = part.strip()
            if part:
                batches.append(part)

    for line in schema_sql.splitlines():
        if line.strip().upper() == "GO":
            statement = "\n".join(current).strip()
            if statement:
                add_statement(statement)
            current = []
        else:
            current.append(line)
    statement = "\n".join(current).strip()
    if statement:
        add_statement(statement)
    return batches


def _postgres_compatible_sql(statement: str) -> str:
    # Retained as a compatibility no-op for older SQL Server-style schema files.
    statement = re.sub(r"\bBIT\b", "BOOLEAN", statement, flags=re.IGNORECASE)
    statement = re.sub(r"VARCHAR\s*\(\s*MAX\s*\)", "TEXT", statement, flags=re.IGNORECASE)
    statement = re.sub(
        r"INT\s+IDENTITY\s*\(\s*1\s*,\s*1\s*\)",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY",
        statement,
        flags=re.IGNORECASE,
    )
    return statement


def _extract_fk_constraints(statement: str) -> list[str]:
    table_match = re.search(r"CREATE\s+TABLE\s+(?P<table>\w+)\s*\(", statement, flags=re.IGNORECASE)
    if not table_match:
        return []

    table_name = table_match.group("table")
    constraints = []
    for match in FK_CONSTRAINT_PATTERN.finditer(statement):
        constraints.append(
            "ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY ({columns}) "
            "REFERENCES {ref_table}({ref_columns}) NOT VALID".format(
                table=table_name,
                name=match.group("name"),
                columns=match.group("columns").strip(),
                ref_table=match.group("ref_table"),
                ref_columns=match.group("ref_columns").strip(),
            )
        )
    return constraints


def _strip_fk_constraints(statement: str) -> str:
    return FK_CONSTRAINT_PATTERN.sub("", statement)


def _schema_statements(schema_path: Path) -> tuple[list[str], list[str], list[str]]:
    translated = [_postgres_compatible_sql(batch) for batch in _split_sql_batches(schema_path.read_text())]
    table_and_check_statements: list[str] = []
    index_statements: list[str] = []
    fk_statements: list[str] = []

    for statement in translated:
        normalized = statement.lstrip().upper()
        if normalized.startswith("CREATE INDEX"):
            index_statements.append(statement)
            continue
        fk_statements.extend(_extract_fk_constraints(statement))
        table_and_check_statements.append(_strip_fk_constraints(statement))

    return table_and_check_statements, index_statements, fk_statements


def _apply_schema(engine, schema_path: Path) -> None:
    if not schema_path.exists():
        raise FileNotFoundError(f"Schema file not found: {schema_path}")

    print(f"Applying schema from {schema_path} without bulk-load FK checks/indexes...")
    table_and_check_statements, _, _ = _schema_statements(schema_path)
    for statement in table_and_check_statements:
        with engine.begin() as conn:
            conn.execute(text(statement))
    print("Schema applied successfully.")


def _apply_post_load_schema(engine, schema_path: Path) -> None:
    import time

    from sqlalchemy.exc import OperationalError

    _, index_statements, fk_statements = _schema_statements(schema_path)
    
    def execute_with_retry(statement: str, max_retries: int = 3):
        for attempt in range(max_retries):
            try:
                with engine.begin() as conn:
                    conn.execute(text(statement))
                return
            except OperationalError as e:
                if "connection has been closed unexpectedly" in str(e) and attempt < max_retries - 1:
                    print(f"Connection dropped. Retrying ({attempt + 1}/{max_retries})...")
                    time.sleep(2)
                    continue
                raise

    print("Creating post-load indexes...")
    for statement in index_statements:
        execute_with_retry(statement)
    print("Post-load indexes ready.")

    if not fk_statements:
        return
    print("Adding foreign-key constraints as NOT VALID...")
    for statement in fk_statements:
        execute_with_retry(statement)
    print("Foreign-key constraints added.")


def _wipe_current_schema(engine) -> None:
    print("Fresh flag detected. Wiping all tables in the current PostgreSQL schema...")
    with engine.begin() as conn:
        table_rows = conn.execute(
            text(
                """
                SELECT quote_ident(table_schema) || '.' || quote_ident(table_name) AS table_name
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
        ).fetchall()
        table_names = [row[0] for row in table_rows]
        if not table_names:
            print("No existing tables found.")
            return

        for table_name in table_names:
            print(f"Dropping table {table_name}...")
        conn.execute(text(f"DROP TABLE IF EXISTS {', '.join(table_names)} CASCADE"))
    print("Database schema wiped successfully.")


def _db_columns(engine, table_name: str) -> list[str]:
    with engine.connect() as conn:
        result = conn.execute(
            text(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = :table_name
                ORDER BY ordinal_position
                """
            ),
            {"table_name": table_name},
        )
        return [row[0] for row in result]


def _quote_ident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _upload_df(engine, table_name: str, df: pd.DataFrame) -> None:
    db_columns = _db_columns(engine, table_name)
    df_columns_by_lower = {column.lower(): column for column in df.columns}
    upload_pairs = [
        (db_column, df_columns_by_lower[db_column.lower()])
        for db_column in db_columns
        if db_column.lower() in df_columns_by_lower
    ]
    if not upload_pairs:
        raise ValueError(f"No upload columns for {table_name}. Data columns: {list(df.columns)}")

    db_upload_columns = [db_column for db_column, _ in upload_pairs]
    df_upload_columns = [df_column for _, df_column in upload_pairs]
    upload_df = df.loc[:, df_upload_columns].copy()
    upload_df.columns = db_upload_columns
    upload_df = upload_df.where(pd.notna(upload_df), None)

    columns_sql = ", ".join(_quote_ident(column) for column in db_upload_columns)
    copy_sql = (
        f"COPY {_quote_ident(table_name)} ({columns_sql}) "
        "FROM STDIN WITH (FORMAT CSV, HEADER TRUE, NULL '')"
    )

    raw_connection = engine.raw_connection()
    try:
        with raw_connection.cursor() as cursor:
            for start in range(0, len(upload_df), COPY_CHUNK_ROWS):
                buffer = StringIO()
                upload_df.iloc[start : start + COPY_CHUNK_ROWS].to_csv(
                    buffer,
                    index=False,
                    header=True,
                    quoting=csv.QUOTE_MINIMAL,
                )
                buffer.seek(0)
                cursor.copy_expert(copy_sql, buffer)
        raw_connection.commit()
    except Exception:
        try:
            raw_connection.rollback()
        except Exception:
            pass
        raise
    finally:
        try:
            raw_connection.close()
        except Exception:
            pass

    print(f"Successfully uploaded {len(upload_df):,} rows to {table_name}.")


def _load_source_frames() -> dict[str, pd.DataFrame]:
    mart_root = Path("data/mart")
    processed_root = Path("data/processed")
    raw_root = Path("data/raw/diginetica")
    return {
        "dim_item": _load_parquet(mart_root / "dim_item.parquet"),
        "dim_model_mart": _load_parquet(mart_root / "dim_model.parquet"),
        "fact_metrics_mart": _load_parquet(mart_root / "fact_metrics.parquet"),
        "fact_recommendation_eval_mart": _load_parquet(mart_root / "fact_recommendation_eval.parquet"),
        "fact_marketing_kpis_mart": _load_parquet(mart_root / "fact_marketing_kpis.parquet"),
        "session_summary": _load_parquet(mart_root / "fact_session_summary.parquet"),
        "clean_item_views": _load_parquet(processed_root / "clean_item_views.parquet"),
        "clean_purchases": _load_parquet(processed_root / "clean_purchases.parquet"),
        "train_clicks": _read_csv(raw_root / "train-clicks.csv"),
        "pbi_session_summary": _read_optional_csv(HELPER_ROOT / "pbi_session_summary.csv"),
        "pbi_model_metrics_summary": _read_optional_csv(HELPER_ROOT / "pbi_model_metrics_summary.csv"),
        "pbi_data_quality_summary": _read_optional_csv(HELPER_ROOT / "pbi_data_quality_summary.csv"),
        "pbi_offline_metrics": _read_optional_csv(HELPER_ROOT / "pbi_offline_metrics.csv"),
        "pbi_hr_by_bucket": _read_optional_csv(HELPER_ROOT / "pbi_hr_by_bucket.csv"),
    }


def _build_dim_date(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dates = pd.concat(
        [
            pd.to_datetime(frames["clean_item_views"]["event_date"], errors="coerce"),
            pd.to_datetime(frames["clean_purchases"]["event_date"], errors="coerce"),
        ],
        ignore_index=True,
    ).dropna()
    dim = pd.DataFrame({"date_key": sorted(dates.dt.date.unique())})
    date_values = pd.to_datetime(dim["date_key"])
    dim["year"] = date_values.dt.year
    dim["month"] = date_values.dt.month
    dim["month_name"] = date_values.dt.month_name()
    dim["week"] = date_values.dt.isocalendar().week.astype("int64")
    dim["day_of_week"] = date_values.dt.dayofweek + 1
    return dim


def _build_dim_product(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dim_item = frames["dim_item"].copy()
    dim_product = pd.DataFrame(
        {
            "item_id": _as_int(dim_item["item_id"]),
            "pricelog2": _as_int(dim_item["pricelog2"]),
            "price_bucket": _price_bucket(dim_item["price_proxy"]),
            "pricelog2_known": dim_item["pricelog2"].notna().astype("int64"),
            "is_price_known": dim_item["price_proxy"].notna(),
            "name_tokens": dim_item.get("product_name_tokens"),
            "category_id": _as_int(dim_item["primary_category_id"]),
        }
    ).drop_duplicates(subset=["item_id"])

    known_items = set(dim_product["item_id"].dropna().astype("int64"))
    clicked_items = set(_as_int(frames["train_clicks"]["itemId"]).dropna().astype("int64"))
    missing_clicked_items = sorted(clicked_items - known_items)
    if missing_clicked_items:
        click_only_products = pd.DataFrame(
            {
                "item_id": pd.Series(missing_clicked_items, dtype="Int64"),
                "pricelog2": pd.Series([pd.NA] * len(missing_clicked_items), dtype="Int64"),
                "price_bucket": "Unknown",
                "pricelog2_known": 0,
                "is_price_known": False,
                "name_tokens": None,
                "category_id": pd.Series([pd.NA] * len(missing_clicked_items), dtype="Int64"),
            }
        )
        dim_product = pd.concat([dim_product, click_only_products], ignore_index=True)

    return dim_product


def _build_dim_user(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    users = pd.concat(
        [
            frames["clean_item_views"]["user_id"],
            frames["clean_purchases"]["user_id"],
            frames["session_summary"]["user_id"],
        ],
        ignore_index=True,
    )
    user_ids = sorted(pd.to_numeric(users, errors="coerce").dropna().astype("int64").unique().tolist())
    dim = pd.DataFrame({"user_id": [ANONYMOUS_USER_ID, *user_ids]})
    dim["is_anonymous"] = dim["user_id"].eq(ANONYMOUS_USER_ID)
    dim["user_type"] = np.where(dim["is_anonymous"], "anonymous", "logged_in")
    return dim


def _build_dim_session(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    sessions = frames["session_summary"].copy()
    views = frames["clean_item_views"]
    purchases = frames["clean_purchases"]

    # Calculate view_to_purchase_depth: count views in session up to first purchase
    first_purchase = purchases.groupby("session_id")["timeframe"].min().reset_index()
    first_purchase.columns = ["session_id", "first_purchase_timeframe"]

    views_with_fp = views.merge(first_purchase, on="session_id", how="inner")
    depths = (
        views_with_fp[views_with_fp["timeframe"] <= views_with_fp["first_purchase_timeframe"]]
        .groupby("session_id")
        .size()
        .reset_index(name="depth")
    )

    df = pd.DataFrame(
        {
            "session_id": _as_int(sessions["session_id"]),
            "user_id": _as_int(sessions["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_type": np.where(sessions["user_id"].isna(), "anonymous", "logged_in"),
            "has_purchase": sessions["has_purchase"].fillna(False).astype(bool),
            "total_views": _as_int(sessions["view_count"], fill_value=0),
        }
    )
    df = df.merge(depths, on="session_id", how="left")
    df["view_to_purchase_depth"] = df["depth"].astype("Int64")
    return df.drop(columns=["depth"]).drop_duplicates(subset=["session_id"])


def _build_dim_query(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    clicks = frames["train_clicks"].copy()
    clicks["query_id"] = _as_int(clicks["queryId"])
    clicks["item_id"] = _as_int(clicks["itemId"])
    return (
        clicks.dropna(subset=["query_id"])
        .groupby("query_id", as_index=False)
        .agg(total_clicks=("item_id", "size"), unique_items=("item_id", "nunique"))
    )


def _build_fact_item_views(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    views = frames["clean_item_views"].copy()
    views = views.sort_values(["session_id", "event_date", "timeframe", "item_id"]).reset_index(drop=True)
    views["view_order"] = views.groupby("session_id").cumcount() + 1
    session_view_count = views.groupby("session_id")["item_id"].transform("size")
    return pd.DataFrame(
        {
            "date_key": _as_date(views["event_date"]),
            "item_id": _as_int(views["item_id"]),
            "user_id": _as_int(views["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_id": _as_int(views["session_id"]),
            "timeframe": _as_int(views["timeframe"], fill_value=0),
            "view_count": 1,
            "view_order": views["view_order"].astype("int64"),
            "is_last_view_in_session": views["view_order"].eq(session_view_count),
        }
    )


def _build_fact_purchases(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    purchases = frames["clean_purchases"].copy()
    return pd.DataFrame(
        {
            "date_key": _as_date(purchases["event_date"]),
            "item_id": _as_int(purchases["item_id"]),
            "user_id": _as_int(purchases["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_id": _as_int(purchases["session_id"]),
            "order_number": _as_int(purchases["order_number"], fill_value=0),
            "purchase_count": 1,
        }
    )


def _build_fact_clicks(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    clicks = frames["train_clicks"].copy()
    return pd.DataFrame(
        {
            "query_id": _as_int(clicks["queryId"]),
            "item_id": _as_int(clicks["itemId"]),
            "timeframe": _as_int(clicks["timeframe"], fill_value=0),
            "click_count": 1,
        }
    ).dropna(subset=["query_id", "item_id"])


def _build_fact_kpi_summary(
    upload_frames: dict[str, pd.DataFrame],
) -> pd.DataFrame:
    views = upload_frames["fact_item_views"]
    purchases = upload_frames["fact_purchases"]
    sessions = upload_frames["dim_session"]
    products = upload_frames["dim_product"]

    # Daily Volume & Conversion base
    daily_v = views.groupby("date_key").agg(total_views=("view_count", "sum")).reset_index()

    daily_p = (
        purchases.groupby("date_key")
        .agg(total_purchases=("purchase_count", "sum"), total_orders=("order_number", "nunique"))
        .reset_index()
    )

    # Daily Sessions & Conversion
    # We need to map session date. fact_item_views is a good proxy for session date.
    sess_date = views.groupby("session_id")["date_key"].min().reset_index()
    sess_metrics = sessions.merge(sess_date, on="session_id", how="inner")

    daily_s = (
        sess_metrics.groupby("date_key")
        .agg(
            total_sessions=("session_id", "count"),
            converted_sessions=("has_purchase", "sum"),
            bounce_sessions=("total_views", lambda x: (x == 1).sum()),
            avg_session_depth=("total_views", "mean"),
            avg_view_to_purchase=("view_to_purchase_depth", "mean"),
        )
        .reset_index()
    )

    # Revenue Score Proxy
    # total_revenue_score = SUM(pricelog2_known) of items purchased
    purch_with_price = purchases.merge(
        products[["item_id", "pricelog2_known"]], on="item_id", how="left"
    )
    daily_rev = (
        purch_with_price.groupby("date_key").agg(total_revenue_score=("pricelog2_known", "sum")).reset_index()
    )

    # Inventory Coverage
    daily_inv_v = views.groupby("date_key").agg(unique_items_viewed=("item_id", "nunique")).reset_index()
    daily_inv_p = (
        purchases.groupby("date_key").agg(unique_items_purchased=("item_id", "nunique")).reset_index()
    )

    # Merge all
    kpi = daily_v.merge(daily_p, on="date_key", how="left")
    kpi = kpi.merge(daily_s, on="date_key", how="left")
    kpi = kpi.merge(daily_rev, on="date_key", how="left")
    kpi = kpi.merge(daily_inv_v, on="date_key", how="left")
    kpi = kpi.merge(daily_inv_p, on="date_key", how="left")

    # Fill NaNs
    cols_to_fill = [
        "total_purchases",
        "total_orders",
        "total_sessions",
        "converted_sessions",
        "bounce_sessions",
        "total_revenue_score",
        "unique_items_viewed",
        "unique_items_purchased",
    ]
    kpi[cols_to_fill] = kpi[cols_to_fill].fillna(0)

    # Calculate Rates
    kpi["conversion_rate"] = kpi["converted_sessions"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["revenue_per_session"] = kpi["total_revenue_score"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["bounce_rate"] = kpi["bounce_sessions"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["inventory_coverage"] = kpi["unique_items_purchased"] / kpi["unique_items_viewed"].replace(0, np.nan)

    # Final cleanup
    kpi = kpi.fillna(0)

    # Cast integer columns explicitly to avoid .0 in CSV (which breaks Postgres integer COPY)
    int_cols = [
        "total_sessions",
        "total_views",
        "total_purchases",
        "total_orders",
        "converted_sessions",
        "bounce_sessions",
        "unique_items_viewed",
        "unique_items_purchased",
    ]
    kpi[int_cols] = kpi[int_cols].astype("int64")

    return kpi


def _normalize_model_label(value: str) -> str:
    lowered = value.strip().lower()
    if lowered in {"sr-gnn", "srgnn", "sr_gnn", "recsys-serving"} or "sr" in lowered:
        return "SR-GNN"
    if "co" in lowered and "occur" in lowered:
        return "Co-occurrence"
    if "pop" in lowered:
        return "Popularity"
    return value


def _build_dim_model_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dim_model = frames["dim_model_mart"].copy()
    offline = frames["pbi_offline_metrics"].copy()

    # Base model from mart
    dim_model["model_key"] = dim_model["model_key"].astype(str)
    label_source = dim_model.get("model_family", dim_model["model_key"]).astype(str)
    dim_model["model_label"] = label_source.apply(_normalize_model_label)

    res = pd.DataFrame(
        {
            "model_key": dim_model["model_key"],
            "model_label": dim_model["model_label"],
            "model_family": dim_model.get("model_family"),
            "model_role": dim_model.get("model_role"),
            "top_k": _as_int(dim_model.get("top_k")),
            "source_type": dim_model.get("source_type"),
            "warning_text": dim_model.get("warning_text"),
        }
    )

    # Add baselines from offline metrics
    if not offline.empty:
        baselines = []
        for model_name in ["Co-occurrence", "Popularity"]:
            if model_name in offline["model"].values:
                baselines.append(
                    {
                        "model_key": model_name.lower().replace("-", "_"),
                        "model_label": model_name,
                        "model_family": "baseline",
                        "model_role": "baseline",
                        "top_k": 20,
                        "source_type": "offline_csv",
                        "warning_text": "Baseline model from report data.",
                    }
                )
        if baselines:
            res = pd.concat([res, pd.DataFrame(baselines)], ignore_index=True)

    return res.drop_duplicates(subset=["model_key"])


def _build_dim_item_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dim_item = frames["dim_item"].copy()
    if dim_item.empty:
        return pd.DataFrame(
            columns=[
                "item_id",
                "pricelog2",
                "price_proxy",
                "product_name_tokens",
                "primary_category_id",
                "category_count",
                "category_ids",
                "item_view_count",
                "item_popularity_bucket",
                "category_name",
            ]
        )

    return pd.DataFrame(
        {
            "item_id": _as_int(dim_item["item_id"]),
            "pricelog2": pd.to_numeric(dim_item.get("pricelog2"), errors="coerce"),
            "price_proxy": pd.to_numeric(dim_item.get("price_proxy"), errors="coerce"),
            "product_name_tokens": dim_item.get("product_name_tokens"),
            "primary_category_id": _as_int(dim_item.get("primary_category_id")),
            "category_count": _as_int(dim_item.get("category_count")),
            "category_ids": _as_int(dim_item.get("category_ids")),
            "item_view_count": _as_int(dim_item.get("item_view_count")),
            "item_popularity_bucket": dim_item.get("item_popularity_bucket"),
            "category_name": pd.Series([None] * len(dim_item)),
        }
    ).drop_duplicates(subset=["item_id"])


def _build_fact_metrics_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    metrics = frames["fact_metrics_mart"].copy()
    offline = frames["pbi_offline_metrics"].copy()

    if metrics.empty and offline.empty:
        return pd.DataFrame(
            columns=["model_key", "metric_name", "metric_value", "k", "metric_scope", "source", "warning_text"]
        )

    res_list = []
    if not metrics.empty:
        metric_name = metrics["metric_name"].astype(str).str.replace("Catalog Coverage@20", "Coverage@20", regex=False)
        res_list.append(
            pd.DataFrame(
                {
                    "model_key": metrics["model_key"].astype(str),
                    "metric_name": metric_name,
                    "metric_value": pd.to_numeric(metrics["metric_value"], errors="coerce"),
                    "k": _as_int(metrics.get("k")),
                    "metric_scope": metrics.get("metric_scope"),
                    "source": metrics.get("source"),
                    "warning_text": metrics.get("warning_text"),
                }
            )
        )

    # Add baseline metrics
    if not offline.empty:
        for _, row in offline.iterrows():
            model_name = row["model"]
            if model_name in ["Co-occurrence", "Popularity"]:
                m_key = model_name.lower().replace("-", "_")
                for m_name, csv_col in [("HR@20", "hr20"), ("MRR@20", "mrr20"), ("Coverage@20", "coverage20")]:
                    res_list.append(
                        pd.DataFrame(
                            [
                                {
                                    "model_key": m_key,
                                    "metric_name": m_name,
                                    "metric_value": row[csv_col],
                                    "k": 20,
                                    "metric_scope": "test_set",
                                    "source": "offline_csv",
                                    "warning_text": None,
                                }
                            ]
                        )
                    )

    return pd.concat(res_list, ignore_index=True) if res_list else pd.DataFrame()


def _build_fact_recommendation_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    eval_df = frames["fact_recommendation_eval_mart"].copy()
    if eval_df.empty:
        return pd.DataFrame(
            columns=[
                "model_key",
                "example_id",
                "session_id",
                "item_id",
                "target_item_id_raw",
                "hit_at_k",
                "target_rank",
                "reciprocal_rank",
                "target_price_proxy",
                "target_primary_category_id",
                "target_item_view_count",
                "target_item_popularity_bucket",
                "captured_value_proxy",
                "is_purchase_session",
                "session_length_bucket",
            ]
        )

    item_id = _as_int(eval_df.get("target_item_id_raw"))
    return pd.DataFrame(
        {
            "model_key": eval_df["model_key"].astype(str),
            "example_id": _as_int(eval_df.get("example_id")),
            "session_id": _as_int(eval_df.get("session_id")),
            "item_id": item_id,
            "target_item_id_raw": item_id,
            "hit_at_k": pd.to_numeric(eval_df.get("hit_at_k"), errors="coerce"),
            "target_rank": _as_int(eval_df.get("target_rank")),
            "reciprocal_rank": pd.to_numeric(eval_df.get("reciprocal_rank"), errors="coerce"),
            "target_price_proxy": pd.to_numeric(eval_df.get("target_price_proxy"), errors="coerce"),
            "target_primary_category_id": _as_int(eval_df.get("target_primary_category_id")),
            "target_item_view_count": _as_int(eval_df.get("target_item_view_count")),
            "target_item_popularity_bucket": eval_df.get("target_item_popularity_bucket"),
            "captured_value_proxy": pd.to_numeric(eval_df.get("captured_value_proxy"), errors="coerce"),
            "is_purchase_session": eval_df.get("is_purchase_session").astype("boolean"),
            "session_length_bucket": eval_df.get("session_length_bucket"),
        }
    )


def _build_fact_marketing_kpis(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    kpis = frames["fact_marketing_kpis_mart"].copy()
    if kpis.empty:
        return pd.DataFrame(columns=["model_key", "k", "kpi_name", "kpi_value", "kpi_scope", "warning_text"])
    return pd.DataFrame(
        {
            "model_key": kpis["model_key"].astype(str),
            "k": _as_int(kpis.get("k")),
            "kpi_name": kpis.get("kpi_name"),
            "kpi_value": pd.to_numeric(kpis.get("kpi_value"), errors="coerce"),
            "kpi_scope": kpis.get("kpi_scope"),
            "warning_text": kpis.get("warning_text"),
        }
    )


def _build_session_summary_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    session = frames["pbi_session_summary"].copy()
    if session.empty:
        return pd.DataFrame(
            columns=[
                "session_id",
                "timeframe",
                "view_count",
                "unique_items_viewed",
                "has_purchase",
                "purchase_count",
                "quantity_sum",
                "session_length_bucket",
                "session_view_bucket_for_conversion",
                "segment",
            ]
        )
    has_purchase = session["has_purchase"] if "has_purchase" in session.columns else pd.Series(False, index=session.index)
    return pd.DataFrame(
        {
            "session_id": _as_int(session.get("session_id")),
            "timeframe": session.get("timeframe"),
            "view_count": _as_int(session.get("view_count"), fill_value=0),
            "unique_items_viewed": _as_int(session.get("unique_items_viewed"), fill_value=0),
            "has_purchase": has_purchase.fillna(False).astype(bool),
            "purchase_count": _as_int(session.get("purchase_count"), fill_value=0),
            "quantity_sum": pd.to_numeric(session.get("quantity_sum"), errors="coerce").fillna(0.0),
            "session_length_bucket": session.get("session_length_bucket"),
            "session_view_bucket_for_conversion": session.get("session_view_bucket_for_conversion"),
            "segment": session.get("segment"),
        }
    ).drop_duplicates(subset=["session_id"])


def _build_model_metrics_summary_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    summary = frames["pbi_model_metrics_summary"].copy()
    offline = frames["pbi_offline_metrics"].copy()

    res_list = []
    if not summary.empty:
        res_list.append(
            pd.DataFrame(
                {
                    "model_key": summary["model_key"].astype(str),
                    "model_label": summary.get("model_label"),
                    "hr_at_20": pd.to_numeric(summary.get("HR@20"), errors="coerce"),
                    "mrr_at_20": pd.to_numeric(summary.get("MRR@20"), errors="coerce"),
                    "coverage_at_20": pd.to_numeric(summary.get("Coverage@20"), errors="coerce"),
                }
            )
        )

    # Add baselines
    if not offline.empty:
        for _, row in offline.iterrows():
            model_name = row["model"]
            if model_name in ["Co-occurrence", "Popularity"]:
                res_list.append(
                    pd.DataFrame(
                        [
                            {
                                "model_key": model_name.lower().replace("-", "_"),
                                "model_label": model_name,
                                "hr_at_20": row["hr20"],
                                "mrr_at_20": row["mrr20"],
                                "coverage_at_20": row["coverage20"],
                            }
                        ]
                    )
                )

    return pd.concat(res_list, ignore_index=True) if res_list else pd.DataFrame()


def _build_data_quality_summary_eval(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    summary = frames["pbi_data_quality_summary"].copy()
    if summary.empty:
        return pd.DataFrame(columns=["metric_name", "metric_value"])
    metric_name = summary["metric_name"] if "metric_name" in summary.columns else pd.Series([], dtype="object")
    metric_value = summary["metric_value"] if "metric_value" in summary.columns else pd.Series([], dtype="object")
    return pd.DataFrame(
        {
            "metric_name": metric_name.astype(str),
            "metric_value": metric_value.astype(str),
        }
    ).drop_duplicates(subset=["metric_name"])


def _build_upload_frames() -> dict[str, pd.DataFrame]:
    frames = _load_source_frames()
    upload_frames = {
        "dim_date": _build_dim_date(frames),
        "dim_product": _build_dim_product(frames),
        "dim_user": _build_dim_user(frames),
        "dim_session": _build_dim_session(frames),
        "dim_query": _build_dim_query(frames),
        "fact_item_views": _build_fact_item_views(frames),
        "fact_purchases": _build_fact_purchases(frames),
        "fact_clicks": _build_fact_clicks(frames),
    }
    upload_frames["fact_kpi_summary"] = _build_fact_kpi_summary(upload_frames)
    upload_frames["dim_model"] = _build_dim_model_eval(frames)
    upload_frames["dim_item"] = _build_dim_item_eval(frames)
    upload_frames["fact_metrics"] = _build_fact_metrics_eval(frames)
    upload_frames["fact_recommendation_eval"] = _build_fact_recommendation_eval(frames)
    upload_frames["fact_marketing_kpis"] = _build_fact_marketing_kpis(frames)
    upload_frames["session_summary"] = _build_session_summary_eval(frames)
    upload_frames["model_metrics_summary"] = _build_model_metrics_summary_eval(frames)
    upload_frames["data_quality_summary"] = _build_data_quality_summary_eval(frames)
    return upload_frames


def upload_to_db(fresh=False):
    postgres_url = _postgres_url()
    if not postgres_url:
        return

    upload_frames = _build_upload_frames()

    engine = create_engine(
        postgres_url,
        pool_pre_ping=True,
        connect_args={
            "keepalives": 1,
            "keepalives_idle": 30,
            "keepalives_interval": 10,
            "keepalives_count": 5,
        },
    )

    if fresh:
        _wipe_current_schema(engine)

    _apply_schema(engine, Path("sql/schema.sql"))

    for table_name in TABLE_LOAD_ORDER:
        print(f"Uploading {table_name}...")
        _upload_df(engine, table_name, upload_frames[table_name])

    _apply_post_load_schema(engine, Path("sql/schema.sql"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Upload DDM Power BI star-schema tables to PostgreSQL.")
    parser.add_argument("--fresh", action="store_true", help="Drop all tables in the current schema before uploading.")
    args = parser.parse_args()

    upload_to_db(fresh=args.fresh)
