import argparse
import csv
import os
import re
from io import StringIO
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text


ANONYMOUS_USER_ID = -1
COPY_CHUNK_ROWS = 100_000
FK_CONSTRAINT_PATTERN = re.compile(
    r",\s*\n\s*CONSTRAINT\s+(?P<name>\w+)\s*\n"
    r"\s*FOREIGN\s+KEY\s*\((?P<columns>[^)]+)\)\s*\n"
    r"\s*REFERENCES\s+(?P<ref_table>\w+)\s*\((?P<ref_columns>[^)]+)\)",
    flags=re.IGNORECASE,
)

TABLE_LOAD_ORDER = [
    "dim_date",
    "dim_product",
    "dim_user",
    "dim_session",
    "dim_query",
    "fact_item_views",
    "fact_purchases",
    "fact_clicks",
    "fact_kpi_summary",
]


def _postgres_url() -> str | None:
    load_dotenv()
    postgres_url = os.getenv("POSTGRES_URL")
    if not postgres_url:
        print("Error: POSTGRES_URL not found in .env")
        return None
    if postgres_url.startswith("postgres://"):
        postgres_url = postgres_url.replace("postgres://", "postgresql://", 1)
    return postgres_url


def _load_parquet(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return pd.read_parquet(path)


def _read_csv(path: Path, **kwargs) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return pd.read_csv(path, sep=";", **kwargs)


def _as_int(series: pd.Series, fill_value: int | None = None) -> pd.Series:
    out = pd.to_numeric(series, errors="coerce")
    if fill_value is not None:
        out = out.fillna(fill_value)
    return out.astype("Int64")


def _as_date(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, errors="coerce").dt.date


def _price_bucket(price_proxy: pd.Series) -> pd.Series:
    price = pd.to_numeric(price_proxy, errors="coerce")
    known = price.notna() & price.gt(0)
    buckets = pd.Series("Unknown", index=price.index, dtype="object")
    if known.any():
        ranked = pd.qcut(
            price[known].rank(method="first"),
            q=4,
            labels=["Low", "Mid", "High", "Premium"],
        )
        buckets.loc[known] = ranked.astype("object")
    return buckets


def _split_sql_batches(schema_sql: str) -> list[str]:
    batches: list[str] = []
    current: list[str] = []

    def add_statement(statement: str) -> None:
        for part in statement.split(";"):
            part = part.strip()
            if part:
                batches.append(part)

    for line in schema_sql.splitlines():
        if line.strip().upper() == "GO":
            statement = "\n".join(current).strip()
            if statement:
                add_statement(statement)
            current = []
        else:
            current.append(line)
    statement = "\n".join(current).strip()
    if statement:
        add_statement(statement)
    return batches


def _postgres_compatible_sql(statement: str) -> str:
    # Retained as a compatibility no-op for older SQL Server-style schema files.
    statement = re.sub(r"\bBIT\b", "BOOLEAN", statement, flags=re.IGNORECASE)
    statement = re.sub(r"VARCHAR\s*\(\s*MAX\s*\)", "TEXT", statement, flags=re.IGNORECASE)
    statement = re.sub(
        r"INT\s+IDENTITY\s*\(\s*1\s*,\s*1\s*\)",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY",
        statement,
        flags=re.IGNORECASE,
    )
    return statement


def _extract_fk_constraints(statement: str) -> list[str]:
    table_match = re.search(r"CREATE\s+TABLE\s+(?P<table>\w+)\s*\(", statement, flags=re.IGNORECASE)
    if not table_match:
        return []

    table_name = table_match.group("table")
    constraints = []
    for match in FK_CONSTRAINT_PATTERN.finditer(statement):
        constraints.append(
            "ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY ({columns}) "
            "REFERENCES {ref_table}({ref_columns}) NOT VALID".format(
                table=table_name,
                name=match.group("name"),
                columns=match.group("columns").strip(),
                ref_table=match.group("ref_table"),
                ref_columns=match.group("ref_columns").strip(),
            )
        )
    return constraints


def _strip_fk_constraints(statement: str) -> str:
    return FK_CONSTRAINT_PATTERN.sub("", statement)


def _schema_statements(schema_path: Path) -> tuple[list[str], list[str], list[str]]:
    translated = [_postgres_compatible_sql(batch) for batch in _split_sql_batches(schema_path.read_text())]
    table_and_check_statements: list[str] = []
    index_statements: list[str] = []
    fk_statements: list[str] = []

    for statement in translated:
        normalized = statement.lstrip().upper()
        if normalized.startswith("CREATE INDEX"):
            index_statements.append(statement)
            continue
        fk_statements.extend(_extract_fk_constraints(statement))
        table_and_check_statements.append(_strip_fk_constraints(statement))

    return table_and_check_statements, index_statements, fk_statements


def _apply_schema(engine, schema_path: Path) -> None:
    if not schema_path.exists():
        raise FileNotFoundError(f"Schema file not found: {schema_path}")

    print(f"Applying schema from {schema_path} without bulk-load FK checks/indexes...")
    table_and_check_statements, _, _ = _schema_statements(schema_path)
    with engine.begin() as conn:
        for statement in table_and_check_statements:
            conn.execute(text(statement))
    print("Schema applied successfully.")


def _apply_post_load_schema(engine, schema_path: Path) -> None:
    _, index_statements, fk_statements = _schema_statements(schema_path)
    print("Creating post-load indexes...")
    with engine.begin() as conn:
        for statement in index_statements:
            conn.execute(text(statement))
    print("Post-load indexes ready.")

    if not fk_statements:
        return
    print("Adding foreign-key constraints as NOT VALID...")
    with engine.begin() as conn:
        for statement in fk_statements:
            conn.execute(text(statement))
    print("Foreign-key constraints added.")


def _wipe_current_schema(engine) -> None:
    print("Fresh flag detected. Wiping all tables in the current PostgreSQL schema...")
    with engine.begin() as conn:
        table_rows = conn.execute(
            text(
                """
                SELECT quote_ident(table_schema) || '.' || quote_ident(table_name) AS table_name
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
        ).fetchall()
        table_names = [row[0] for row in table_rows]
        if not table_names:
            print("No existing tables found.")
            return

        for table_name in table_names:
            print(f"Dropping table {table_name}...")
        conn.execute(text(f"DROP TABLE IF EXISTS {', '.join(table_names)} CASCADE"))
    print("Database schema wiped successfully.")


def _db_columns(engine, table_name: str) -> list[str]:
    with engine.connect() as conn:
        result = conn.execute(
            text(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = :table_name
                ORDER BY ordinal_position
                """
            ),
            {"table_name": table_name},
        )
        return [row[0] for row in result]


def _quote_ident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _upload_df(engine, table_name: str, df: pd.DataFrame) -> None:
    db_columns = _db_columns(engine, table_name)
    df_columns_by_lower = {column.lower(): column for column in df.columns}
    upload_pairs = [
        (db_column, df_columns_by_lower[db_column.lower()])
        for db_column in db_columns
        if db_column.lower() in df_columns_by_lower
    ]
    if not upload_pairs:
        raise ValueError(f"No upload columns for {table_name}. Data columns: {list(df.columns)}")

    db_upload_columns = [db_column for db_column, _ in upload_pairs]
    df_upload_columns = [df_column for _, df_column in upload_pairs]
    upload_df = df.loc[:, df_upload_columns].copy()
    upload_df.columns = db_upload_columns
    upload_df = upload_df.where(pd.notna(upload_df), None)

    columns_sql = ", ".join(_quote_ident(column) for column in db_upload_columns)
    copy_sql = (
        f"COPY {_quote_ident(table_name)} ({columns_sql}) "
        "FROM STDIN WITH (FORMAT CSV, HEADER TRUE, NULL '')"
    )

    raw_connection = engine.raw_connection()
    try:
        with raw_connection.cursor() as cursor:
            for start in range(0, len(upload_df), COPY_CHUNK_ROWS):
                buffer = StringIO()
                upload_df.iloc[start : start + COPY_CHUNK_ROWS].to_csv(
                    buffer,
                    index=False,
                    header=True,
                    quoting=csv.QUOTE_MINIMAL,
                )
                buffer.seek(0)
                cursor.copy_expert(copy_sql, buffer)
        raw_connection.commit()
    except Exception:
        try:
            raw_connection.rollback()
        except Exception:
            pass
        raise
    finally:
        try:
            raw_connection.close()
        except Exception:
            pass

    print(f"Successfully uploaded {len(upload_df):,} rows to {table_name}.")


def _load_source_frames() -> dict[str, pd.DataFrame]:
    mart_root = Path("data/mart")
    processed_root = Path("data/processed")
    raw_root = Path("data/raw/diginetica")
    return {
        "dim_item": _load_parquet(mart_root / "dim_item.parquet"),
        "session_summary": _load_parquet(mart_root / "fact_session_summary.parquet"),
        "clean_item_views": _load_parquet(processed_root / "clean_item_views.parquet"),
        "clean_purchases": _load_parquet(processed_root / "clean_purchases.parquet"),
        "train_clicks": _read_csv(raw_root / "train-clicks.csv"),
    }


def _build_dim_date(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dates = pd.concat(
        [
            pd.to_datetime(frames["clean_item_views"]["event_date"], errors="coerce"),
            pd.to_datetime(frames["clean_purchases"]["event_date"], errors="coerce"),
        ],
        ignore_index=True,
    ).dropna()
    dim = pd.DataFrame({"date_key": sorted(dates.dt.date.unique())})
    date_values = pd.to_datetime(dim["date_key"])
    dim["year"] = date_values.dt.year
    dim["month"] = date_values.dt.month
    dim["month_name"] = date_values.dt.month_name()
    dim["week"] = date_values.dt.isocalendar().week.astype("int64")
    dim["day_of_week"] = date_values.dt.dayofweek + 1
    return dim


def _build_dim_product(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    dim_item = frames["dim_item"].copy()
    dim_product = pd.DataFrame(
        {
            "item_id": _as_int(dim_item["item_id"]),
            "pricelog2": _as_int(dim_item["pricelog2"]),
            "price_bucket": _price_bucket(dim_item["price_proxy"]),
            "pricelog2_known": dim_item["pricelog2"].notna().astype("int64"),
            "is_price_known": dim_item["price_proxy"].notna(),
            "name_tokens": dim_item.get("product_name_tokens"),
            "category_id": _as_int(dim_item["primary_category_id"]),
        }
    ).drop_duplicates(subset=["item_id"])

    known_items = set(dim_product["item_id"].dropna().astype("int64"))
    clicked_items = set(_as_int(frames["train_clicks"]["itemId"]).dropna().astype("int64"))
    missing_clicked_items = sorted(clicked_items - known_items)
    if missing_clicked_items:
        click_only_products = pd.DataFrame(
            {
                "item_id": pd.Series(missing_clicked_items, dtype="Int64"),
                "pricelog2": pd.Series([pd.NA] * len(missing_clicked_items), dtype="Int64"),
                "price_bucket": "Unknown",
                "pricelog2_known": 0,
                "is_price_known": False,
                "name_tokens": None,
                "category_id": pd.Series([pd.NA] * len(missing_clicked_items), dtype="Int64"),
            }
        )
        dim_product = pd.concat([dim_product, click_only_products], ignore_index=True)

    return dim_product


def _build_dim_user(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    users = pd.concat(
        [
            frames["clean_item_views"]["user_id"],
            frames["clean_purchases"]["user_id"],
            frames["session_summary"]["user_id"],
        ],
        ignore_index=True,
    )
    user_ids = sorted(pd.to_numeric(users, errors="coerce").dropna().astype("int64").unique().tolist())
    dim = pd.DataFrame({"user_id": [ANONYMOUS_USER_ID, *user_ids]})
    dim["is_anonymous"] = dim["user_id"].eq(ANONYMOUS_USER_ID)
    dim["user_type"] = np.where(dim["is_anonymous"], "anonymous", "logged_in")
    return dim


def _build_dim_session(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    sessions = frames["session_summary"].copy()
    views = frames["clean_item_views"]
    purchases = frames["clean_purchases"]

    # Calculate view_to_purchase_depth: count views in session up to first purchase
    first_purchase = purchases.groupby("session_id")["timeframe"].min().reset_index()
    first_purchase.columns = ["session_id", "first_purchase_timeframe"]

    views_with_fp = views.merge(first_purchase, on="session_id", how="inner")
    depths = (
        views_with_fp[views_with_fp["timeframe"] <= views_with_fp["first_purchase_timeframe"]]
        .groupby("session_id")
        .size()
        .reset_index(name="depth")
    )

    df = pd.DataFrame(
        {
            "session_id": _as_int(sessions["session_id"]),
            "user_id": _as_int(sessions["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_type": np.where(sessions["user_id"].isna(), "anonymous", "logged_in"),
            "has_purchase": sessions["has_purchase"].fillna(False).astype(bool),
            "total_views": _as_int(sessions["view_count"], fill_value=0),
        }
    )
    df = df.merge(depths, on="session_id", how="left")
    df["view_to_purchase_depth"] = df["depth"].astype("Int64")
    return df.drop(columns=["depth"]).drop_duplicates(subset=["session_id"])


def _build_dim_query(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    clicks = frames["train_clicks"].copy()
    clicks["query_id"] = _as_int(clicks["queryId"])
    clicks["item_id"] = _as_int(clicks["itemId"])
    return (
        clicks.dropna(subset=["query_id"])
        .groupby("query_id", as_index=False)
        .agg(total_clicks=("item_id", "size"), unique_items=("item_id", "nunique"))
    )


def _build_fact_item_views(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    views = frames["clean_item_views"].copy()
    views = views.sort_values(["session_id", "event_date", "timeframe", "item_id"]).reset_index(drop=True)
    views["view_order"] = views.groupby("session_id").cumcount() + 1
    session_view_count = views.groupby("session_id")["item_id"].transform("size")
    return pd.DataFrame(
        {
            "date_key": _as_date(views["event_date"]),
            "item_id": _as_int(views["item_id"]),
            "user_id": _as_int(views["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_id": _as_int(views["session_id"]),
            "timeframe": _as_int(views["timeframe"], fill_value=0),
            "view_count": 1,
            "view_order": views["view_order"].astype("int64"),
            "is_last_view_in_session": views["view_order"].eq(session_view_count),
        }
    )


def _build_fact_purchases(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    purchases = frames["clean_purchases"].copy()
    return pd.DataFrame(
        {
            "date_key": _as_date(purchases["event_date"]),
            "item_id": _as_int(purchases["item_id"]),
            "user_id": _as_int(purchases["user_id"], fill_value=ANONYMOUS_USER_ID),
            "session_id": _as_int(purchases["session_id"]),
            "order_number": _as_int(purchases["order_number"], fill_value=0),
            "purchase_count": 1,
        }
    )


def _build_fact_clicks(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    clicks = frames["train_clicks"].copy()
    return pd.DataFrame(
        {
            "query_id": _as_int(clicks["queryId"]),
            "item_id": _as_int(clicks["itemId"]),
            "timeframe": _as_int(clicks["timeframe"], fill_value=0),
            "click_count": 1,
        }
    ).dropna(subset=["query_id", "item_id"])


def _build_fact_kpi_summary(
    upload_frames: dict[str, pd.DataFrame],
) -> pd.DataFrame:
    views = upload_frames["fact_item_views"]
    purchases = upload_frames["fact_purchases"]
    sessions = upload_frames["dim_session"]
    products = upload_frames["dim_product"]

    # Daily Volume & Conversion base
    daily_v = views.groupby("date_key").agg(total_views=("view_count", "sum")).reset_index()

    daily_p = (
        purchases.groupby("date_key")
        .agg(total_purchases=("purchase_count", "sum"), total_orders=("order_number", "nunique"))
        .reset_index()
    )

    # Daily Sessions & Conversion
    # We need to map session date. fact_item_views is a good proxy for session date.
    sess_date = views.groupby("session_id")["date_key"].min().reset_index()
    sess_metrics = sessions.merge(sess_date, on="session_id", how="inner")

    daily_s = (
        sess_metrics.groupby("date_key")
        .agg(
            total_sessions=("session_id", "count"),
            converted_sessions=("has_purchase", "sum"),
            bounce_sessions=("total_views", lambda x: (x == 1).sum()),
            avg_session_depth=("total_views", "mean"),
            avg_view_to_purchase=("view_to_purchase_depth", "mean"),
        )
        .reset_index()
    )

    # Revenue Score Proxy
    # total_revenue_score = SUM(pricelog2_known) of items purchased
    purch_with_price = purchases.merge(
        products[["item_id", "pricelog2_known"]], on="item_id", how="left"
    )
    daily_rev = (
        purch_with_price.groupby("date_key").agg(total_revenue_score=("pricelog2_known", "sum")).reset_index()
    )

    # Inventory Coverage
    daily_inv_v = views.groupby("date_key").agg(unique_items_viewed=("item_id", "nunique")).reset_index()
    daily_inv_p = (
        purchases.groupby("date_key").agg(unique_items_purchased=("item_id", "nunique")).reset_index()
    )

    # Merge all
    kpi = daily_v.merge(daily_p, on="date_key", how="left")
    kpi = kpi.merge(daily_s, on="date_key", how="left")
    kpi = kpi.merge(daily_rev, on="date_key", how="left")
    kpi = kpi.merge(daily_inv_v, on="date_key", how="left")
    kpi = kpi.merge(daily_inv_p, on="date_key", how="left")

    # Fill NaNs
    cols_to_fill = [
        "total_purchases",
        "total_orders",
        "total_sessions",
        "converted_sessions",
        "bounce_sessions",
        "total_revenue_score",
        "unique_items_viewed",
        "unique_items_purchased",
    ]
    kpi[cols_to_fill] = kpi[cols_to_fill].fillna(0)

    # Calculate Rates
    kpi["conversion_rate"] = kpi["converted_sessions"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["revenue_per_session"] = kpi["total_revenue_score"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["bounce_rate"] = kpi["bounce_sessions"] / kpi["total_sessions"].replace(0, np.nan)
    kpi["inventory_coverage"] = kpi["unique_items_purchased"] / kpi["unique_items_viewed"].replace(0, np.nan)

    # Final cleanup
    kpi = kpi.fillna(0)

    # Cast integer columns explicitly to avoid .0 in CSV (which breaks Postgres integer COPY)
    int_cols = [
        "total_sessions",
        "total_views",
        "total_purchases",
        "total_orders",
        "converted_sessions",
        "bounce_sessions",
        "unique_items_viewed",
        "unique_items_purchased",
    ]
    kpi[int_cols] = kpi[int_cols].astype("int64")

    return kpi


def _build_upload_frames() -> dict[str, pd.DataFrame]:
    frames = _load_source_frames()
    upload_frames = {
        "dim_date": _build_dim_date(frames),
        "dim_product": _build_dim_product(frames),
        "dim_user": _build_dim_user(frames),
        "dim_session": _build_dim_session(frames),
        "dim_query": _build_dim_query(frames),
        "fact_item_views": _build_fact_item_views(frames),
        "fact_purchases": _build_fact_purchases(frames),
        "fact_clicks": _build_fact_clicks(frames),
    }
    upload_frames["fact_kpi_summary"] = _build_fact_kpi_summary(upload_frames)
    return upload_frames


def upload_to_db(fresh=False):
    postgres_url = _postgres_url()
    if not postgres_url:
        return

    engine = create_engine(postgres_url)

    if fresh:
        _wipe_current_schema(engine)

    _apply_schema(engine, Path("sql/schema.sql"))

    upload_frames = _build_upload_frames()
    for table_name in TABLE_LOAD_ORDER:
        print(f"Uploading {table_name}...")
        _upload_df(engine, table_name, upload_frames[table_name])

    _apply_post_load_schema(engine, Path("sql/schema.sql"))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Upload DDM Power BI star-schema tables to PostgreSQL.")
    parser.add_argument("--fresh", action="store_true", help="Drop all tables in the current schema before uploading.")
    args = parser.parse_args()

    upload_to_db(fresh=args.fresh)
