table 'public dim_session'
	lineageTag: 0d3297b9-ec1c-4de9-b5f9-1aa05b57ca99

	column session_id
		dataType: int64
		formatString: "0"
		lineageTag: 03648dde-a446-463b-be10-d570e6d28da9
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: int64
		formatString: "0"
		lineageTag: 877a11cd-edf7-41fa-a69d-ffdc91ff3e32
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column session_type
		dataType: string
		lineageTag: 658105af-9355-410c-a1a6-5423f715eb42
		summarizeBy: none
		sourceColumn: session_type

		annotation SummarizationSetBy = Automatic

	column has_purchase
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 54e195b4-cb6f-4c9c-bff7-3d35495da5a7
		summarizeBy: none
		sourceColumn: has_purchase

		annotation SummarizationSetBy = Automatic

	column total_views
		dataType: int64
		formatString: "0"
		lineageTag: d6ac380b-c8f0-4b0d-96ea-7a6daf924ebb
		summarizeBy: sum
		sourceColumn: total_views

		annotation SummarizationSetBy = Automatic

	column view_to_purchase_depth
		dataType: int64
		formatString: "0"
		lineageTag: a343649c-abea-4774-bd64-e107f1207afb
		summarizeBy: sum
		sourceColumn: view_to_purchase_depth

		annotation SummarizationSetBy = Automatic

	measure 'Total Sessions' = DISTINCTCOUNT('public dim_session'[session_id])
		formatString: "#,0"
		displayFolder: 'KPI Page 1'

	measure 'Purchasing Sessions' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[has_purchase] = TRUE()))
		formatString: "#,0"
		displayFolder: 'KPI Page 1'

	measure 'Conversion Rate' = DIVIDE([Purchasing Sessions], [Total Sessions])
		formatString: "0.00%"
		displayFolder: 'KPI Page 1'

	measure 'Avg Session Depth' = AVERAGE('public dim_session'[total_views])
		formatString: "0.00"
		displayFolder: 'KPI Page 2'

	measure 'Bounce Sessions' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] <= 1))
		formatString: "#,0"
		displayFolder: 'KPI Page 2'

	measure 'Bounce Rate' = DIVIDE([Bounce Sessions], [Total Sessions])
		formatString: "0.00%"
		displayFolder: 'KPI Page 2'

	measure 'Avg Session Duration (min)' = AVERAGEX(VALUES('public dim_session'[session_id]), VAR _min_tf = CALCULATE(MIN('public fact_item_views'[timeframe])) VAR _max_tf = CALCULATE(MAX('public fact_item_views'[timeframe])) RETURN DIVIDE(_max_tf - _min_tf, 60.0))
		formatString: "0.00"
		displayFolder: 'KPI Page 2'

	measure 'Anonymous Sessions' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[session_type] = "anonymous"))
		formatString: "#,0"
		displayFolder: 'Graph Page 1'

	measure 'Identified Sessions' = [Total Sessions] - [Anonymous Sessions]
		formatString: "#,0"
		displayFolder: 'Graph Page 1'

	measure 'Percent Anonymous Sessions' = DIVIDE([Anonymous Sessions], [Total Sessions])
		formatString: "0.00%"
		displayFolder: 'Graph Page 1'

	measure 'Percent Identified Sessions' = DIVIDE([Identified Sessions], [Total Sessions])
		formatString: "0.00%"
		displayFolder: 'Graph Page 1'

	measure 'Avg Actions Anonymous Session' = CALCULATE([Avg Session Depth], KEEPFILTERS('public dim_session'[session_type] = "anonymous"))
		formatString: "0.00"
		displayFolder: 'Graph Page 1'

	measure 'Avg Actions Identified Session' = CALCULATE([Avg Session Depth], KEEPFILTERS('public dim_session'[session_type] <> "anonymous"))
		formatString: "0.00"
		displayFolder: 'Graph Page 1'

	measure 'Sessions (Views 1-5)' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] >= 1), KEEPFILTERS('public dim_session'[total_views] <= 5))
		formatString: "#,0"
		displayFolder: 'Graph Page 2'

	measure 'Sessions (Views 6-10)' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] >= 6), KEEPFILTERS('public dim_session'[total_views] <= 10))
		formatString: "#,0"
		displayFolder: 'Graph Page 2'

	measure 'Sessions (Views 11-20)' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] >= 11), KEEPFILTERS('public dim_session'[total_views] <= 20))
		formatString: "#,0"
		displayFolder: 'Graph Page 2'

	measure 'Sessions (Views 21-30)' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] >= 21), KEEPFILTERS('public dim_session'[total_views] <= 30))
		formatString: "#,0"
		displayFolder: 'Graph Page 2'

	measure 'Sessions (Views 31-100)' = CALCULATE([Total Sessions], KEEPFILTERS('public dim_session'[total_views] >= 31), KEEPFILTERS('public dim_session'[total_views] <= 100))
		formatString: "#,0"
		displayFolder: 'Graph Page 2'

	measure 'CR (Views 1-5)' = CALCULATE([Conversion Rate], KEEPFILTERS('public dim_session'[total_views] >= 1), KEEPFILTERS('public dim_session'[total_views] <= 5))
		formatString: "0.00%"
		displayFolder: 'Graph Page 2'

	measure 'CR (Views 6-10)' = CALCULATE([Conversion Rate], KEEPFILTERS('public dim_session'[total_views] >= 6), KEEPFILTERS('public dim_session'[total_views] <= 10))
		formatString: "0.00%"
		displayFolder: 'Graph Page 2'

	measure 'CR (Views 11-20)' = CALCULATE([Conversion Rate], KEEPFILTERS('public dim_session'[total_views] >= 11), KEEPFILTERS('public dim_session'[total_views] <= 20))
		formatString: "0.00%"
		displayFolder: 'Graph Page 2'

	measure 'CR (Views 21-30)' = CALCULATE([Conversion Rate], KEEPFILTERS('public dim_session'[total_views] >= 21), KEEPFILTERS('public dim_session'[total_views] <= 30))
		formatString: "0.00%"
		displayFolder: 'Graph Page 2'

	measure 'CR (Views 31-100)' = CALCULATE([Conversion Rate], KEEPFILTERS('public dim_session'[total_views] >= 31), KEEPFILTERS('public dim_session'[total_views] <= 100))
		formatString: "0.00%"
		displayFolder: 'Graph Page 2'

	partition 'public dim_session' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("recsys-sql-lytlong-e04a.b.aivencloud.com:22307", "defaultdb"),
				    public_dim_session = Source{[Schema="public",Item="dim_session"]}[Data]
				in
				    public_dim_session

	annotation PBI_ResultType = Table
