table 'SR-GNN Measures'
	lineageTag: a7769970-d72b-4f9e-a89c-4877f0d06983

	measure HR@20 =
			VAR MetricFromSummary =
			    AVERAGE ( 'public model_metrics_summary'[hr_at_20] )
			VAR MetricFromFact =
			    CALCULATE (
			        AVERAGE ( 'public fact_metrics'[metric_value] ),
			        'public fact_metrics'[metric_name] IN {"HR@20", "HR", "hr20"},
			        'public fact_metrics'[k] IN {20, BLANK()}
			    )
			VAR MetricFromEval =
			    AVERAGE ( 'public fact_recommendation_eval'[hit_at_k] )
			RETURN
			    COALESCE ( MetricFromSummary, MetricFromFact, MetricFromEval )
		formatString: 0.0000
		lineageTag: b691f162-426b-4f0f-8c01-789a74f4b961

	measure MRR@20 =
			VAR MetricFromSummary =
			    AVERAGE ( 'public model_metrics_summary'[mrr_at_20] )
			VAR MetricFromFact =
			    CALCULATE (
			        AVERAGE ( 'public fact_metrics'[metric_value] ),
			        'public fact_metrics'[metric_name] IN {"MRR@20", "MRR", "mrr20"},
			        'public fact_metrics'[k] IN {20, BLANK()}
			    )
			VAR MetricFromEval =
			    AVERAGE ( 'public fact_recommendation_eval'[reciprocal_rank] )
			RETURN
			    COALESCE ( MetricFromSummary, MetricFromFact, MetricFromEval )
		formatString: 0.0000
		lineageTag: d63f35a1-7c5b-402a-a92c-567e914d86c4

	measure Coverage@20 =
			VAR MetricFromSummary =
			    AVERAGE ( 'public model_metrics_summary'[coverage_at_20] )
			VAR MetricFromFact =
			    CALCULATE (
			        AVERAGE ( 'public fact_metrics'[metric_value] ),
			        'public fact_metrics'[metric_name] IN {"Coverage@20", "Catalog Coverage@20", "coverage20", "Coverage"},
			        'public fact_metrics'[k] IN {20, BLANK()}
			    )
			VAR MetricFromEval =
			    DIVIDE (
			        DISTINCTCOUNT ( 'public fact_recommendation_eval'[target_item_id_raw] ),
			        DISTINCTCOUNT ( 'public dim_item'[item_id] )
			    )
			RETURN
			    COALESCE ( MetricFromSummary, MetricFromFact, MetricFromEval )
		formatString: 0.0%
		lineageTag: f491e2b5-3d5a-4e2b-b89c-d47e814d86c4

	measure 'AOV Proxy' =
			CALCULATE (
			    DIVIDE ( 'public fact_purchases'[Total Revenue Proxy], 'public fact_purchases'[Total Orders] ),
			    REMOVEFILTERS ( 'public dim_model' )
			)
		formatString: #,0
		lineageTag: 3571f162-426b-4f0f-8c01-789a74f4b961

	column Placeholder
		dataType: string
		lineageTag: 87d215b7-7233-45d8-8aca-9ab616a4714b
		summarizeBy: none
		sourceColumn: Placeholder

		annotation SummarizationSetBy = Automatic

	partition Partition = m
		mode: import
		source =
				let
				    Source = #table({"Placeholder"}, {{"Measures"}})
				in
				    Source

