-- PostgreSQL star schema for Diginetica Power BI analytics.
-- Grain: product/session/query dimensions plus item-view, purchase, and click facts.

CREATE TABLE dim_date (
    date_key     DATE        NOT NULL PRIMARY KEY,
    year         INTEGER     NOT NULL,
    month        INTEGER     NOT NULL,
    month_name   VARCHAR(20) NOT NULL,
    week         INTEGER     NOT NULL,
    day_of_week  INTEGER     NOT NULL
);

CREATE TABLE dim_product (
    item_id          INTEGER     NOT NULL PRIMARY KEY,
    pricelog2        INTEGER,
    price_bucket     VARCHAR(20) NOT NULL,
    pricelog2_known  INTEGER,
    is_price_known   BOOLEAN     NOT NULL,
    name_tokens      TEXT,
    category_id      INTEGER,

    CONSTRAINT ck_dim_product_price_bucket
        CHECK (price_bucket IN ('Unknown', 'Low', 'Mid', 'High', 'Premium'))
);

CREATE TABLE dim_user (
    user_id       INTEGER     NOT NULL PRIMARY KEY,
    is_anonymous  BOOLEAN     NOT NULL,
    user_type     VARCHAR(20) NOT NULL,

    CONSTRAINT ck_dim_user_user_type
        CHECK (user_type IN ('logged_in', 'anonymous'))
);

CREATE TABLE dim_session (
    session_id              INTEGER     NOT NULL PRIMARY KEY,
    user_id                 INTEGER     NOT NULL,
    session_type            VARCHAR(20) NOT NULL,
    has_purchase            BOOLEAN     NOT NULL,
    total_views             INTEGER     NOT NULL,
    view_to_purchase_depth  INTEGER,

    CONSTRAINT ck_dim_session_session_type
        CHECK (session_type IN ('logged_in', 'anonymous')),

    CONSTRAINT fk_dim_session_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id)
);

CREATE TABLE dim_query (
    query_id      INTEGER NOT NULL PRIMARY KEY,
    total_clicks  INTEGER NOT NULL,
    unique_items  INTEGER NOT NULL
);

CREATE TABLE fact_item_views (
    view_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key                 DATE    NOT NULL,
    item_id                  INTEGER NOT NULL,
    user_id                  INTEGER NOT NULL,
    session_id               INTEGER NOT NULL,
    timeframe                BIGINT  NOT NULL,
    view_count               INTEGER NOT NULL DEFAULT 1,
    view_order               INTEGER NOT NULL,
    is_last_view_in_session  BOOLEAN NOT NULL,

    CONSTRAINT ck_fact_item_views_view_count
        CHECK (view_count = 1),

    CONSTRAINT fk_fact_item_views_dim_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_item_views_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id),

    CONSTRAINT fk_fact_item_views_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id),

    CONSTRAINT fk_fact_item_views_dim_session
        FOREIGN KEY (session_id)
        REFERENCES dim_session(session_id)
);

CREATE TABLE fact_purchases (
    purchase_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key        DATE    NOT NULL,
    item_id         INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    session_id      INTEGER NOT NULL,
    order_number    INTEGER NOT NULL,
    purchase_count  INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT ck_fact_purchases_purchase_count
        CHECK (purchase_count = 1),

    CONSTRAINT fk_fact_purchases_dim_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_purchases_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id),

    CONSTRAINT fk_fact_purchases_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id),

    CONSTRAINT fk_fact_purchases_dim_session
        FOREIGN KEY (session_id)
        REFERENCES dim_session(session_id)
);

CREATE TABLE fact_clicks (
    click_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id     INTEGER NOT NULL,
    item_id      INTEGER NOT NULL,
    timeframe    BIGINT  NOT NULL,
    click_count  INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT ck_fact_clicks_click_count
        CHECK (click_count = 1),

    CONSTRAINT fk_fact_clicks_dim_query
        FOREIGN KEY (query_id)
        REFERENCES dim_query(query_id),

    CONSTRAINT fk_fact_clicks_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id)
);

CREATE TABLE fact_kpi_summary (
    date_key                DATE    NOT NULL PRIMARY KEY,
    -- Volume
    total_sessions          INTEGER NOT NULL,
    total_views             INTEGER NOT NULL,
    total_purchases         INTEGER NOT NULL,
    total_orders            INTEGER NOT NULL,
    -- Revenue proxy
    total_revenue_score     DOUBLE PRECISION NOT NULL,
    -- Conversion
    converted_sessions      INTEGER NOT NULL,
    conversion_rate         DOUBLE PRECISION NOT NULL,
    revenue_per_session     DOUBLE PRECISION NOT NULL,
    -- Engagement
    avg_session_depth       DOUBLE PRECISION NOT NULL,
    avg_view_to_purchase    DOUBLE PRECISION,
    bounce_sessions         INTEGER NOT NULL,
    bounce_rate             DOUBLE PRECISION NOT NULL,
    -- Inventory
    unique_items_viewed     INTEGER NOT NULL,
    unique_items_purchased  INTEGER NOT NULL,
    inventory_coverage      DOUBLE PRECISION NOT NULL,

    CONSTRAINT fk_fact_kpi_summary_dim_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);

COMMENT ON TABLE fact_kpi_summary IS 'Pre-aggregated KPI table. Grain = 1 ngày. Refresh sau ETL. Dùng cho Power BI KPI cards và trend charts.';


CREATE INDEX ix_fact_item_views_date_key
    ON fact_item_views(date_key);

CREATE INDEX ix_fact_item_views_item_id
    ON fact_item_views(item_id);

CREATE INDEX ix_fact_item_views_user_id
    ON fact_item_views(user_id);

CREATE INDEX ix_fact_item_views_session_id
    ON fact_item_views(session_id);

CREATE INDEX ix_fact_purchases_date_key
    ON fact_purchases(date_key);

CREATE INDEX ix_fact_purchases_item_id
    ON fact_purchases(item_id);

CREATE INDEX ix_fact_purchases_user_id
    ON fact_purchases(user_id);

CREATE INDEX ix_fact_purchases_session_id
    ON fact_purchases(session_id);

CREATE INDEX ix_fact_clicks_query_id
    ON fact_clicks(query_id);

CREATE INDEX ix_fact_clicks_item_id
    ON fact_clicks(item_id);


CREATE TABLE dim_model (
    model_key     VARCHAR(100) NOT NULL PRIMARY KEY,
    model_label   VARCHAR(100) NOT NULL,
    model_family  VARCHAR(100),
    model_role    VARCHAR(100),
    top_k         INTEGER,
    source_type   VARCHAR(100),
    warning_text  TEXT
);

CREATE TABLE dim_item (
    item_id                  INTEGER NOT NULL PRIMARY KEY,
    pricelog2                DOUBLE PRECISION,
    price_proxy              DOUBLE PRECISION,
    product_name_tokens      TEXT,
    primary_category_id      INTEGER,
    category_count           INTEGER,
    category_ids             BIGINT,
    item_view_count          INTEGER,
    item_popularity_bucket   VARCHAR(30),
    category_name            VARCHAR(255)
);

CREATE TABLE fact_metrics (
    metric_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key      VARCHAR(100)      NOT NULL,
    metric_name    VARCHAR(100)      NOT NULL,
    metric_value   DOUBLE PRECISION  NOT NULL,
    k              INTEGER,
    metric_scope   VARCHAR(100),
    source         VARCHAR(100),
    warning_text   TEXT,

    CONSTRAINT fk_fact_metrics_dim_model
        FOREIGN KEY (model_key)
        REFERENCES dim_model(model_key)
);

CREATE TABLE fact_recommendation_eval (
    rec_eval_id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key                       VARCHAR(100)     NOT NULL,
    example_id                      BIGINT           NOT NULL,
    session_id                      BIGINT,
    item_id                         INTEGER,
    target_item_id_raw              INTEGER,
    hit_at_k                        DOUBLE PRECISION,
    target_rank                     INTEGER,
    reciprocal_rank                 DOUBLE PRECISION,
    target_price_proxy              DOUBLE PRECISION,
    target_primary_category_id      INTEGER,
    target_item_view_count          INTEGER,
    target_item_popularity_bucket   VARCHAR(30),
    captured_value_proxy            DOUBLE PRECISION,
    is_purchase_session             BOOLEAN,
    session_length_bucket           VARCHAR(20),

    CONSTRAINT fk_fact_recommendation_eval_dim_model
        FOREIGN KEY (model_key)
        REFERENCES dim_model(model_key),

    CONSTRAINT fk_fact_recommendation_eval_dim_item
        FOREIGN KEY (item_id)
        REFERENCES dim_item(item_id)
);

CREATE TABLE fact_marketing_kpis (
    kpi_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key      VARCHAR(100)      NOT NULL,
    k              INTEGER,
    kpi_name       VARCHAR(150)      NOT NULL,
    kpi_value      DOUBLE PRECISION  NOT NULL,
    kpi_scope      VARCHAR(100),
    warning_text   TEXT,

    CONSTRAINT fk_fact_marketing_kpis_dim_model
        FOREIGN KEY (model_key)
        REFERENCES dim_model(model_key)
);

CREATE TABLE session_summary (
    session_id                          BIGINT          NOT NULL PRIMARY KEY,
    timeframe                           VARCHAR(20)     NOT NULL,
    view_count                          INTEGER         NOT NULL,
    unique_items_viewed                 INTEGER         NOT NULL,
    has_purchase                        BOOLEAN         NOT NULL,
    purchase_count                      INTEGER         NOT NULL,
    quantity_sum                        DOUBLE PRECISION NOT NULL,
    session_length_bucket               VARCHAR(20),
    session_view_bucket_for_conversion  VARCHAR(20),
    segment                             VARCHAR(50)
);

CREATE TABLE model_metrics_summary (
    model_key     VARCHAR(100) NOT NULL PRIMARY KEY,
    model_label   VARCHAR(100) NOT NULL,
    hr_at_20      DOUBLE PRECISION,
    mrr_at_20     DOUBLE PRECISION,
    coverage_at_20 DOUBLE PRECISION,

    CONSTRAINT fk_model_metrics_summary_dim_model
        FOREIGN KEY (model_key)
        REFERENCES dim_model(model_key)
);

CREATE TABLE data_quality_summary (
    metric_name   VARCHAR(100) NOT NULL PRIMARY KEY,
    metric_value  TEXT
);


CREATE INDEX ix_fact_metrics_model_key
    ON fact_metrics(model_key);

CREATE INDEX ix_fact_metrics_metric_name
    ON fact_metrics(metric_name);

CREATE INDEX ix_fact_recommendation_eval_model_key
    ON fact_recommendation_eval(model_key);

CREATE INDEX ix_fact_recommendation_eval_session_id
    ON fact_recommendation_eval(session_id);

CREATE INDEX ix_fact_recommendation_eval_item_id
    ON fact_recommendation_eval(item_id);

CREATE INDEX ix_fact_marketing_kpis_model_key
    ON fact_marketing_kpis(model_key);

CREATE INDEX ix_fact_marketing_kpis_kpi_name
    ON fact_marketing_kpis(kpi_name);

CREATE INDEX ix_session_summary_timeframe
    ON session_summary(timeframe);
