-- PostgreSQL star schema for Diginetica Power BI analytics.
-- Grain: product/session/query dimensions plus item-view, purchase, and click facts.

CREATE TABLE dim_date (
    date_key     DATE        NOT NULL PRIMARY KEY,
    year         INTEGER     NOT NULL,
    month        INTEGER     NOT NULL,
    month_name   VARCHAR(20) NOT NULL,
    week         INTEGER     NOT NULL,
    day_of_week  INTEGER     NOT NULL
);

CREATE TABLE dim_product (
    item_id          INTEGER     NOT NULL PRIMARY KEY,
    pricelog2        INTEGER,
    price_bucket     VARCHAR(20) NOT NULL,
    pricelog2_known  INTEGER,
    is_price_known   BOOLEAN     NOT NULL,
    name_tokens      TEXT,
    category_id      INTEGER,

    CONSTRAINT ck_dim_product_price_bucket
        CHECK (price_bucket IN ('Unknown', 'Low', 'Mid', 'High', 'Premium'))
);

CREATE TABLE dim_user (
    user_id       INTEGER     NOT NULL PRIMARY KEY,
    is_anonymous  BOOLEAN     NOT NULL,
    user_type     VARCHAR(20) NOT NULL,

    CONSTRAINT ck_dim_user_user_type
        CHECK (user_type IN ('logged_in', 'anonymous'))
);

CREATE TABLE dim_session (
    session_id              INTEGER     NOT NULL PRIMARY KEY,
    user_id                 INTEGER     NOT NULL,
    session_type            VARCHAR(20) NOT NULL,
    has_purchase            BOOLEAN     NOT NULL,
    total_views             INTEGER     NOT NULL,
    view_to_purchase_depth  INTEGER,

    CONSTRAINT ck_dim_session_session_type
        CHECK (session_type IN ('logged_in', 'anonymous')),

    CONSTRAINT fk_dim_session_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id)
);

CREATE TABLE dim_query (
    query_id      INTEGER NOT NULL PRIMARY KEY,
    total_clicks  INTEGER NOT NULL,
    unique_items  INTEGER NOT NULL
);

CREATE TABLE fact_item_views (
    view_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key                 DATE    NOT NULL,
    item_id                  INTEGER NOT NULL,
    user_id                  INTEGER NOT NULL,
    session_id               INTEGER NOT NULL,
    timeframe                BIGINT  NOT NULL,
    view_count               INTEGER NOT NULL DEFAULT 1,
    view_order               INTEGER NOT NULL,
    is_last_view_in_session  BOOLEAN NOT NULL,

    CONSTRAINT ck_fact_item_views_view_count
        CHECK (view_count = 1),

    CONSTRAINT fk_fact_item_views_dim_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_item_views_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id),

    CONSTRAINT fk_fact_item_views_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id),

    CONSTRAINT fk_fact_item_views_dim_session
        FOREIGN KEY (session_id)
        REFERENCES dim_session(session_id)
);

CREATE TABLE fact_purchases (
    purchase_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key        DATE    NOT NULL,
    item_id         INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    session_id      INTEGER NOT NULL,
    order_number    INTEGER NOT NULL,
    purchase_count  INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT ck_fact_purchases_purchase_count
        CHECK (purchase_count = 1),

    CONSTRAINT fk_fact_purchases_dim_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_purchases_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id),

    CONSTRAINT fk_fact_purchases_dim_user
        FOREIGN KEY (user_id)
        REFERENCES dim_user(user_id),

    CONSTRAINT fk_fact_purchases_dim_session
        FOREIGN KEY (session_id)
        REFERENCES dim_session(session_id)
);

CREATE TABLE fact_clicks (
    click_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id     INTEGER NOT NULL,
    item_id      INTEGER NOT NULL,
    timeframe    BIGINT  NOT NULL,
    click_count  INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT ck_fact_clicks_click_count
        CHECK (click_count = 1),

    CONSTRAINT fk_fact_clicks_dim_query
        FOREIGN KEY (query_id)
        REFERENCES dim_query(query_id),

    CONSTRAINT fk_fact_clicks_dim_product
        FOREIGN KEY (item_id)
        REFERENCES dim_product(item_id)
);

CREATE INDEX ix_fact_item_views_date_key
    ON fact_item_views(date_key);

CREATE INDEX ix_fact_item_views_item_id
    ON fact_item_views(item_id);

CREATE INDEX ix_fact_item_views_user_id
    ON fact_item_views(user_id);

CREATE INDEX ix_fact_item_views_session_id
    ON fact_item_views(session_id);

CREATE INDEX ix_fact_purchases_date_key
    ON fact_purchases(date_key);

CREATE INDEX ix_fact_purchases_item_id
    ON fact_purchases(item_id);

CREATE INDEX ix_fact_purchases_user_id
    ON fact_purchases(user_id);

CREATE INDEX ix_fact_purchases_session_id
    ON fact_purchases(session_id);

CREATE INDEX ix_fact_clicks_query_id
    ON fact_clicks(query_id);

CREATE INDEX ix_fact_clicks_item_id
    ON fact_clicks(item_id);
